collectors_quest_local_homepage:
    pattern:  /
    defaults: { _controller: CollectorsQuestLocalBundle:Default:index }

collectors_quest_local_privacy:
    pattern:  /privacy
    defaults: { _controller: CollectorsQuestLocalBundle:Default:privacy }
