parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    foursquare_id:     'MWPCILL1FDZVMWDNFFM2DBZPXA1LE0HB5LWG02EFM0MSBGX4'
    foursquare_secret: 'OBNVHOT0RSK2K5E5BHDFI4JZOWYYNK0U5CZHIXL0L3ZM4BF2'

    locale:            en
    secret:            '9c2d78f02cad61b637ea0595e8f753c2'
